REM mvn install:install-file -DgroupId=com.adobe.flex.framework -DartifactId=playerglobal -Dversion=4.1.0.16076 -Dclassifier=cs_CZ -Dpackaging=rb.swc -Dfile="C:\Program Files\Adobe\Adobe Flash Builder 4\sdks\4.1.0.16076\frameworks\libs\player\10.0\playerglobal.swc"
REM mvn install:install-file -DgroupId=com.adobe.flexbuilder.dcrad -DartifactId=playerfds -Dversion=4.0.1.277662 -Dpackaging=swc -Dfile="C:\Program Files\Adobe\Adobe Flash Builder 4\plugins\com.adobe.flexbuilder.dcrad_4.0.1.277662\fiberSwcs\4.0\libs\playerfds.swc" -DgeneratePom=true
REM mvn install:install-file -DgroupId=com.adobe.flexbuilder.dcrad -DartifactId=fiber -Dversion=4.0.1.277662 -Dpackaging=swc -Dfile="C:\Program Files\Adobe\Adobe Flash Builder 4\plugins\com.adobe.flexbuilder.dcrad_4.0.1.277662\fiberSwcs\4.0\libs\fiber.swc" -DgeneratePom=true
REM mvn install:install-file -DgroupId=com.adobe.flexbuilder.dcrad -DartifactId=serializers -Dversion=4.0.1.277662 -Dpackaging=swc -Dfile="C:\Program Files\Adobe\Adobe Flash Builder 4\plugins\com.adobe.flexbuilder.dcrad_4.0.1.277662\dcradSwcs\4.0\libs\serializers.swc" -DgeneratePom=true
REM mvn install:install-file -DgroupId=com.kitd.fusion.ServicesTestBed -DartifactId=preloader -Dversion=1.0 -Dpackaging=swc -Dfile="C:\Users\jozef.chutka\work\flex\Fusion\ServicesTestBed\libs\preloader.swc" -DgeneratePom=true
REM mvn install:install-file -DgroupId=com.adobe.flexbuilder.dcrad -DartifactId=fiber_rb -Dversion=4.0.1.277662 -Dpackaging=swc -Dfile="C:\Program Files\Adobe\Adobe Flash Builder 4\plugins\com.adobe.flexbuilder.dcrad_4.0.1.277662\fiberSwcs\4.0\locale\fiber_rb.swc" -DgeneratePom=true
REM mvn install:install-file -DgroupId=org.robotlegs -DartifactId=robotlegs-framework -Dversion=1.4.0 -Dpackaging=swc -Dfile="C:\Users\jozef.chutka\work\flex\LIBS\swc\robotlegs-framework-v1.4.0.swc" -DgeneratePom=true
REM mvn install:install-file -DgroupId=com.asual.swfaddress -DartifactId=SWFAddress -Dversion=2.4 -Dpackaging=swc -Dfile="C:\Users\jozef.chutka\work\flex\LIBS\swc\SWFAddress.swc" -DgeneratePom=true

CALL MVN install:install-file -DgroupId=com.adobe.flex.framework -DartifactId=automation -Dversion=4.1.0.16076 -Dpackaging=swc -Dfile="c:\Users\jozef.chutka\work\sdks\flex\4.1.0.16076\frameworks\libs\automation\automation.swc" -DgeneratePom=true
CALL MVN install:install-file -DgroupId=com.adobe.flex.framework -DartifactId=automation-agent -Dversion=4.1.0.16076 -Dpackaging=swc -Dfile="c:\Users\jozef.chutka\work\sdks\flex\4.1.0.16076\frameworks\libs\automation\automation_agent.swc" -DgeneratePom=true
CALL MVN install:install-file -DgroupId=com.adobe.flex.framework -DartifactId=automation-dmv -Dversion=4.1.0.16076 -Dpackaging=swc -Dfile="c:\Users\jozef.chutka\work\sdks\flex\4.1.0.16076\frameworks\libs\automation\automation_dmv.swc" -DgeneratePom=true
CALL MVN install:install-file -DgroupId=com.adobe.flex.framework -DartifactId=automation-flashflexkit -Dversion=4.1.0.16076 -Dpackaging=swc -Dfile="c:\Users\jozef.chutka\work\sdks\flex\4.1.0.16076\frameworks\libs\automation\automation_flashflexkit.swc" -DgeneratePom=true
CALL MVN install:install-file -DgroupId=com.adobe.flex.framework -DartifactId=automation-spark -Dversion=4.1.0.16076 -Dpackaging=swc -Dfile="c:\Users\jozef.chutka\work\sdks\flex\4.1.0.16076\frameworks\libs\automation\automation_spark.swc" -DgeneratePom=true
CALL MVN install:install-file -DgroupId=com.adobe.flex.framework -DartifactId=qtp -Dversion=4.1.0.16076 -Dpackaging=swc -Dfile="c:\Users\jozef.chutka\work\sdks\flex\4.1.0.16076\frameworks\libs\automation\qtp.swc" -DgeneratePom=true